---
title: "R Notebook"
output: html_notebook
---

## Import 1st Dataset
```{r}
rm(list=ls())
library(tidyverse)
library(summarytools)
library(stargazer)
#load data
load("~/Desktop/git_project/merged_data_CC.Rda")
```
## Analytics

### Descriptive Statistics
```{r}
is.na(merged_data)
names(merged_data)
```

```{r}
merged_data <- merged_data %>% mutate_if(is.character,as.numeric)
mean_scale_score <- "Mean Scale Score"
school_number <- "School Number.x"
grade_band <- "Grade Band"
prompt_admin_response <- "Admin1-The school administration promptly responds to my concerns"
parent_input <- "Admin9-Parents have the opportunity to give input into the school's decisions"  
pride_for_student_art <- "Creative1-Student work in the arts is displayed or presented in my child's school" 
clean_school <- "Environ1-The school building is clean and well maintained"
parent_response <- "Estimated Parent Response Rate1"


save(merged_data, file="merged_data_CC.Rda")

school_number <- as.numeric(school_number)
mean_scale_score <- as.numeric(mean_scale_score)
prompt_admin_response <- as.numeric(prompt_admin_response)
parent_input <- as.numeric(parent_input)
parent_response <- as.numeric(parent_response)
as.numeric(merged_data[[1]])

mean(merged_data, na.rm=TRUE)
```


```{r}
with(merged_data, descr(parent_response))
```
### Frequency Table

```{r}
with(merged_data, freq(prompt_admin_response))
```


### Contingency Table

```{r}
with(merged_data, ctable(mean_scale_score, school_number, prop="c"))
```

### Correlation Table

```{r}
with(merged_data, cor(select(merged_data, school_number, prompt_admin_response, clean_school, mean_scale_score)))
```

### Linear Regression

```{r}
fit_lr <- lm(mean_scale_score ~ prompt_admin_response, data=merged_data)
summary(fit_lr)
```

### Multiple Regression

```{r}
fit_mr <- lm(mean_scale_score ~ prompt_admin_response + clean_school, data=merged_data)
summary(fit_mr)
```

### Regression Tables

```{r}
fit_model_1 <- lm(mean_scale_score ~ prompt_admin_response + clean_school, data=merged_data)
fit_model_2 <- lm(mean_scale_score ~ prompt_admin_response + parent_input, data=merged_data)
fit_model_3 <- lm(mean_scale_score ~ prompt_admin_response + parent_response + clean_school, data=analytic)
suppressWarnings(
  stargazer(fit_model_1, fit_model_2, fit_model_3, type="text")
)
```
